import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideNav from './sideNav/sideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='grid grid-cols-[auto_2fr] h-screen overflow-hidden'>
        <SideNav/>
        {children}
        </body>
    </html>
  )
}
